name: Lint & Typecheck

on:
  pull_request:
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - ".eslintrc.*"
      - ".prettierrc*"
  push:
    branches: [main, master]
    paths:
      - "**/*.ts"
      - "**/*.tsx"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22.x, 20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Typecheck (tsc --noEmit)
        run: npm run typecheck

      - name: ESLint
        run: npm run lint

      - name: Prettier (check)
        run: npm run format
